### ISSUE TITLE
0xc000007b on Windows 10

### ISSUE THREAD

**Issue by liuyuancv** [springzfx/point-cloud-annotation-tool#17]
Hi，I met errors for the generated point_cloud_annotation_tool.exe file.
I build the tool with 0 errors. I also build VTK8.0, PCL-1.8.1 and QT5.7 successfully.
However, when I run the generated .exe file, the error is 应用程序无法正常启动(0xc000007b)
Moreover, in the same folder, only two files are generated.
Anyone knows why?
Because I build VTK8.0, PCL-1.8.1 and QT5.7 successfully, so I think the errors are related to the last step which is to build the annotation tool.

**Comment by liuyuancv** [comment]
The problem has been solved and it's a stupid mistake I made.

**Comment by hai715** [comment]
请问是怎么解决的，我也是只生成两个文件，build都成功了，但是运行报错

**Comment by hai715** [comment]
> The problem has been solved and it's a stupid mistake I made.

请问是怎么解决的，我也是只生成两个文件，build都成功了，但是运行报错
