### ISSUE TITLE
How to install/execute on windows

### ISSUE THREAD

**Issue by Do-Hwan** [springzfx/point-cloud-annotation-tool#5]
Hi, how to install/execute on windows?

**Comment by springzfx** [comment]
I used Qt Creator for this project. It supports Cmake directly. So try it. 
Google for more detail.

**Comment by ALei-imotion** [comment]
> I used Qt Creator for this project. It supports Cmake directly. So try it.
> Google for more detail.

Hi, I want to know how to run it in Ubuntu 16.04?
What environment does it depend on?
