### ISSUE TITLE
make error: undefined reference to `vtkRenderingGL2PSOpenGL2_AutoInit_Construct()

### ISSUE THREAD

**Issue by zjbaby** [springzfx/point-cloud-annotation-tool#8]
I've installed pcl1.9、vtk8.2 and Qt5, But I get an error when compiling the code:
CMakeFiles/point_cloud_annotation_tool.dir/visualizer.cpp.o: In function vtkRenderingOpenGL2_AutoInit::vtkRenderingOpenGL2_AutoInit()': visualizer.cpp:(.text._ZN28vtkRenderingOpenGL2_AutoInitC2Ev[_ZN28vtkRenderingOpenGL2_AutoInitC5Ev]+0xd): undefined reference to vtkRenderingGL2PSOpenGL2_AutoInit_Construct()'
CMakeFiles/point_cloud_annotation_tool.dir/visualizer.cpp.o: In function vtkRenderingOpenGL2_AutoInit::~vtkRenderingOpenGL2_AutoInit()': visualizer.cpp:(.text._ZN28vtkRenderingOpenGL2_AutoInitD2Ev[_ZN28vtkRenderingOpenGL2_AutoInitD5Ev]+0xd): undefined reference to vtkRenderingGL2PSOpenGL2_AutoInit_Destruct()'
CMakeFiles/point_cloud_annotation_tool.dir/visualizer.cpp.o: In function Ui_MainWindow::setupUi(QMainWindow*)': visualizer.cpp:(.text._ZN13Ui_MainWindow7setupUiEP11QMainWindow[_ZN13Ui_MainWindow7setupUiEP11QMainWindow]+0xb4e): undefined reference to QVTKWidget::QVTKWidget(QWidget*, QFlagsQt::WindowType)'
collect2: error: ld returned 1 exit status
CMakeFiles/point_cloud_annotation_tool.dir/build.make:426: recipe for target 'point_cloud_annotation_tool' failed
make[2]: *** [point_cloud_annotation_tool] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/point_cloud_annotation_tool.dir/all' failed
make[1]: *** [CMakeFiles/point_cloud_annotation_tool.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

How to fix it?

**Comment by springzfx** [comment]
If you are in archlinux, make sure these optional dependency installed. Other distribution should be smiliar :
![image](https://user-images.githubusercontent.com/8992037/71877168-7ef91d80-3163-11ea-8f01-bbda964c825b.png)

**Comment by zjbaby** [comment]
I solve the problem, thanks!~

**Comment by zzwlinux** [comment]
> I solve the problem, thanks!~
I have met the same issue, could you show the way you slove the problem?

**Comment by zzwlinux** [comment]
I have met the same issue, could you show the way you slove the problem?

**Comment by zzwlinux** [comment]
I have met the same issue, could you show the way you slove the problem? @zjbaby

**Comment by LinhanDai** [comment]
> I solve the problem, thanks!~

I have met the same problem, please show the way you slove the problem
